
name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2
        
      - name: Build for testing
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          build-for-testing

  ios:
    name: iOS
    runs-on: macos-latest
    steps:

      - name: Test iPhone 8
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' \
          test

      - name: Test iPhone 8 Plus
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=15.0' \
          test

      - name: Test iPhone 11
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0' \
          test

      - name: Test iPhone 11 Pro
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0' \
          test

      - name: Test iPhone 11 Pro Max
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=15.0' \
          test

      - name: Test iPhone 12
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' \
          test

      - name: Test iPhone 12 Pro
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0' \
          test

      - name: Test iPhone 12 Pro Max
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=15.0' \
          test

      - name: Test iPhone 12 mini
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.0' \
          test

      - name: Test iPhone 13
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' \
          test

      - name: Test iPhone 13 Pro
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.0' \
          test

      - name: Test iPhone 13 Pro Max
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.0' \
          test

      - name: Test iPhone 13 mini
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.0' \
          test

      - name: Test iPhone SE (2nd generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=15.0' \
          test

      - name: Test iPod Touch (7th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS 
          \-destination 'platform=iOS Simulator,name=iPod Touch (7th generation),OS=15.0' \
          test

  ipados:
    name: iPadOS
    runs-on: macos-latest
    steps:
      - name: Test iPad (7th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad (7th generation),OS=15.0' \
          test

      - name: Test iPad (8th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad (8th generation),OS=15.0' \
          test

      - name: Test iPad (9th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad (9th generation),OS=15.0' \
          test

      - name: Test iPad Air (3th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad Air (3th generation),OS=15.0' \
          test

      - name: Test iPad Air (4th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad Air (4th generation),OS=15.0' \
          test

      - name: Test iPad Pro (9.7-inch)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad Pro (9.7-inch),OS=15.0' \
          test

      - name: Test iPad Pro (11-inch) (2nd generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad Pro (11-inch) (2nd generation),OS=15.0' \
          test

      - name: Test iPad Pro (11-inch) (3rd generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad Pro (11-inch) (3rd generation),OS=15.0' \
          test

      - name: Test iPad Pro (12.9-inch) (4th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (4th generation),OS=15.0' \
          test

      - name: Test iPad Pro (12.9-inch) (5th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (5th generation),OS=15.0' \
          test

      - name: Test iPad mini (6th generation)
        run: >-
          xcodebuild \
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace \
          -scheme Tests\ iOS \
          -destination 'platform=iOS Simulator,name=iPad mini (6th generation),OS=15.0' \
          test
