
name: iOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  tests:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Install utilities
        run: >-
          gem install xcpretty

      - name: Checkout latest commit
        uses: actions/checkout@v2

      - name: Test iPhone 8
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 8 Plus
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 11
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 11 Pro
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS 
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 11 Pro Max
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 12
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 12 Pro
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 12 Pro Max
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 12 mini
        run: >-
          xcodebuild 
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 13
        run: >-
          xcodebuild 
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 13 Pro
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 13 Pro Max
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone 13 mini
        run: >-
          xcodebuild 
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPhone SE (2nd generation)
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Test iPod Touch (7th generation)
        run: >-
          xcodebuild
          -workspace Demo/FireUI\ Demo.xcodeproj/project.xcworkspace
          -scheme Tests\ iOS
          -destination 'platform=iOS Simulator,name=iPod Touch (7th generation),OS=15.0'
          test
          | xcpretty && exit ${PIPESTATUS[0]}
