name: Firebase TestLab

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  build:
    name: Install build tools and utilities
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install xcpretty
        run: >-
          gem install xcpretty

      - name: Build for testing
        run: >-
          xcodebuild
          -allowProvisioningUpdates
          -project "Demo/FireUI Demo.xcodeproj"
          -scheme "Tests iOS"
          -derivedDataPath DerivedData
          -sdk iphoneos build-for-testing
          | xcpretty && exit ${PIPESTATUS[0]}

      - name: Zip build to "Tests/iOSTests.zip"
        run: >-
          cd DerivedData/Index/Build/Products : zip -r "Tests/iOSTests.zip" "Debug-iphoneos" "Tests iOS_iphoneos15.0-arm64.xctestrun"

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Run tests on firebase
        run: >-
          if gcloud firebase test ios run --test Tests/iOSTests.zip --timeout 2m
          then
              echo "Test matrix successfully finished"
          else
              echo "Test matrix exited abnormally with non-zero exit code: " $?
              exit $?
          fi
          echo "View test results on Firebase TestLab: https://console.firebase.google.com/project/${{ secrets.PROJECT_ID }}/testlab/histories"
